version: "3.4"

networks:
  frontend:
  backend:

services:

  webmvc:
    build: 
      context: .\src\Services\Web\WebMvc
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
      - CatalogUrl=http://catalog
    container_name: webshop
    ports:
      - "5500:80"
    networks:
      - frontend 
    depends_on:
      - catalog
   
  catalog:
    build:  
      context: .\src\Services\ProductCatalogApi
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
    container_name: catalogapi
    ports:
      - "5000:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    container_name: mssqldata
    ports:
      - "1402:1433" 
    networks:
      - backend
    environment:
      SA_PASSWORD: "ProductAPI(!)"
      ACCEPT_EULA: "Y"

    